import type { Node } from '@xyflow/react'
import type { Point, TaskPriority, TerminalNodeData, WorkspaceSpaceState } from '../../../types'
import type { ContextMenuState } from '../types'
import type { WorkspaceCanvasActionRefs } from './useActionRefs'
import { useWorkspaceCanvasNodeDeleteConfirmation } from './useNodeDeleteConfirmation'
import { useWorkspaceCanvasTaskCreator } from './useTaskCreator'
import { useWorkspaceCanvasTaskEditor } from './useTaskEditor'

type SetNodes = (
  updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
  options?: { syncLayout?: boolean },
) => void

export function useWorkspaceCanvasTaskWindows({
  taskTagOptions,
  contextMenu,
  setContextMenu,
  nodesRef,
  setNodes,
  spacesRef,
  onSpacesChange,
  onRequestPersistFlush,
  suggestTaskTitle,
  createTaskNode,
  closeNode,
  actionRefs,
}: {
  taskTagOptions: string[]
  contextMenu: ContextMenuState | null
  setContextMenu: React.Dispatch<React.SetStateAction<ContextMenuState | null>>
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  setNodes: SetNodes
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onRequestPersistFlush?: () => void
  suggestTaskTitle: (
    requirement: string,
  ) => Promise<{ title: string; priority: TaskPriority; tags: string[] }>
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
  ) => Node<TerminalNodeData> | null
  closeNode: (nodeId: string) => Promise<void>
  actionRefs: WorkspaceCanvasActionRefs
}) {
  const {
    taskCreator,
    setTaskCreator,
    openTaskCreator,
    closeTaskCreator,
    generateTaskTitle,
    createTask,
  } = useWorkspaceCanvasTaskCreator({
    contextMenu,
    setContextMenu,
    taskTagOptions,
    nodesRef,
    setNodes,
    spacesRef,
    onSpacesChange,
    onRequestPersistFlush,
    suggestTaskTitle,
    createTaskNode,
  })

  const { taskEditor, setTaskEditor, closeTaskEditor, generateTaskEditorTitle, saveTaskEdits } =
    useWorkspaceCanvasTaskEditor({
      nodesRef,
      setNodes,
      onRequestPersistFlush,
      setContextMenu,
      suggestTaskTitle,
      taskTagOptions,
      openTaskEditorRef: actionRefs.openTaskEditorRef,
    })

  const { nodeDeleteConfirmation, setNodeDeleteConfirmation, confirmNodeDelete } =
    useWorkspaceCanvasNodeDeleteConfirmation({
      nodesRef,
      closeNode,
      requestNodeDeleteRef: actionRefs.requestNodeDeleteRef,
    })

  return {
    taskCreator,
    setTaskCreator,
    openTaskCreator,
    closeTaskCreator,
    generateTaskTitle,
    createTask,
    taskEditor,
    setTaskEditor,
    closeTaskEditor,
    generateTaskEditorTitle,
    saveTaskEdits,
    nodeDeleteConfirmation,
    setNodeDeleteConfirmation,
    confirmNodeDelete,
  }
}
