import type { Node } from '@xyflow/react'
import type { StandardWindowSizeBucket } from '@contexts/settings/domain/agentSettings'
import type {
  DocumentNodeData,
  ImageNodeData,
  NodeFrame,
  Point,
  Size,
  TerminalNodeData,
  TaskPriority,
} from '../../../types'
import type { WorkspaceSpaceState } from '../../../types'
import type { NodeLabelColorOverride } from '@shared/types/labelColor'
import type { CreateNodeInput, NodePlacementOptions, ShowWorkspaceCanvasMessage } from '../types'

export interface CreateNoteNodeOptions {
  placementStrategy?: 'default' | 'right-no-push'
  placement?: NodePlacementOptions
}

export interface UseWorkspaceCanvasNodesStoreParams {
  nodes: Node<TerminalNodeData>[]
  spacesRef: React.MutableRefObject<WorkspaceSpaceState[]>
  onNodesChange: (nodes: Node<TerminalNodeData>[]) => void
  onSpacesChange: (spaces: WorkspaceSpaceState[]) => void
  onRequestPersistFlush?: () => void
  onShowMessage?: ShowWorkspaceCanvasMessage
  onNodeCreated?: (nodeId: string) => void
  standardWindowSizeBucket: StandardWindowSizeBucket
}

export interface UseWorkspaceCanvasNodesStoreResult {
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  pendingScrollbackByNodeRef: React.MutableRefObject<Map<string, string>>
  isNodeDraggingRef: React.MutableRefObject<boolean>
  setNodes: (
    updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    options?: { syncLayout?: boolean },
  ) => void
  upsertNode: (nextNode: Node<TerminalNodeData>) => void
  bumpAgentLaunchToken: (nodeId: string) => number
  clearAgentLaunchToken: (nodeId: string) => void
  isAgentLaunchTokenCurrent: (nodeId: string, token: number) => boolean
  closeNode: (nodeId: string) => Promise<void>
  normalizePosition: (nodeId: string, desired: Point, size: Size) => Point
  resizeNode: (nodeId: string, desiredFrame: NodeFrame) => void
  applyPendingScrollbacks: (targetNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[]
  updateNodeScrollback: (nodeId: string, scrollback: string) => void
  updateTerminalTitle: (nodeId: string, title: string) => void
  renameTerminalTitle: (nodeId: string, title: string) => void
  setNodeLabelColorOverride: (nodeIds: string[], labelColorOverride: NodeLabelColorOverride) => void
  updateNoteText: (nodeId: string, text: string) => void
  createNodeForSession: (input: CreateNodeInput) => Promise<Node<TerminalNodeData> | null>
  createNoteNode: (anchor: Point, options?: CreateNoteNodeOptions) => Node<TerminalNodeData> | null
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
    placement?: NodePlacementOptions,
  ) => Node<TerminalNodeData> | null
  createImageNode: (
    anchor: Point,
    image: ImageNodeData,
    placement?: NodePlacementOptions,
  ) => Node<TerminalNodeData> | null
  createDocumentNode: (
    anchor: Point,
    document: DocumentNodeData,
    placement?: NodePlacementOptions,
  ) => Node<TerminalNodeData> | null
}
