import { useCallback, useEffect, useRef } from 'react'
import type { Node } from '@xyflow/react'
import type { Point, Size, TerminalNodeData, TaskPriority } from '../../../types'
import {
  clampSizeToNonOverlapping,
  findNearestFreePosition,
  isPositionAvailable,
} from '../../../utils/collision'
import { DEFAULT_SIZE, MIN_SIZE, TASK_SIZE } from '../constants'
import type { CreateNodeInput } from '../types'

export function useWorkspaceCanvasNodesStore({
  nodes,
  onNodesChange,
  onRequestPersistFlush,
}: {
  nodes: Node<TerminalNodeData>[]
  onNodesChange: (nodes: Node<TerminalNodeData>[]) => void
  onRequestPersistFlush?: () => void
}): {
  nodesRef: React.MutableRefObject<Node<TerminalNodeData>[]>
  pendingScrollbackByNodeRef: React.MutableRefObject<Map<string, string>>
  isNodeDraggingRef: React.MutableRefObject<boolean>
  setNodes: (
    updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
    options?: { syncLayout?: boolean },
  ) => void
  upsertNode: (nextNode: Node<TerminalNodeData>) => void
  bumpAgentLaunchToken: (nodeId: string) => number
  clearAgentLaunchToken: (nodeId: string) => void
  isAgentLaunchTokenCurrent: (nodeId: string, token: number) => boolean
  closeNode: (nodeId: string) => Promise<void>
  normalizePosition: (nodeId: string, desired: Point, size: Size) => Point
  resizeNode: (nodeId: string, desiredSize: Size) => void
  applyPendingScrollbacks: (targetNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[]
  updateNodeScrollback: (nodeId: string, scrollback: string) => void
  updateTerminalTitle: (nodeId: string, title: string) => void
  createNodeForSession: (input: CreateNodeInput) => Promise<Node<TerminalNodeData> | null>
  createTaskNode: (
    anchor: Point,
    title: string,
    requirement: string,
    autoGeneratedTitle: boolean,
    priority: TaskPriority,
    tags: string[],
  ) => Node<TerminalNodeData> | null
} {
  const nodesRef = useRef(nodes)
  const agentLaunchTokenByNodeIdRef = useRef<Map<string, number>>(new Map())
  const pendingScrollbackByNodeRef = useRef<Map<string, string>>(new Map())
  const isNodeDraggingRef = useRef(false)

  useEffect(() => {
    nodesRef.current = nodes
  }, [nodes])

  const setNodes = useCallback(
    (
      updater: (prevNodes: Node<TerminalNodeData>[]) => Node<TerminalNodeData>[],
      options: { syncLayout?: boolean } = {},
    ) => {
      const previousNodes = nodesRef.current
      const nextNodes = updater(previousNodes)

      if (nextNodes === previousNodes) {
        return
      }

      nodesRef.current = nextNodes
      onNodesChange(nextNodes)

      if (options.syncLayout ?? true) {
        window.dispatchEvent(new Event('cove:terminal-layout-sync'))
      }
    },
    [onNodesChange],
  )

  const upsertNode = useCallback(
    (nextNode: Node<TerminalNodeData>) => {
      setNodes(prevNodes => prevNodes.map(node => (node.id === nextNode.id ? nextNode : node)))
    },
    [setNodes],
  )

  const bumpAgentLaunchToken = useCallback((nodeId: string): number => {
    const next = (agentLaunchTokenByNodeIdRef.current.get(nodeId) ?? 0) + 1
    agentLaunchTokenByNodeIdRef.current.set(nodeId, next)
    return next
  }, [])

  const clearAgentLaunchToken = useCallback((nodeId: string): void => {
    agentLaunchTokenByNodeIdRef.current.delete(nodeId)
  }, [])

  const isAgentLaunchTokenCurrent = useCallback((nodeId: string, token: number): boolean => {
    return (agentLaunchTokenByNodeIdRef.current.get(nodeId) ?? 0) === token
  }, [])

  const closeNode = useCallback(
    async (nodeId: string) => {
      clearAgentLaunchToken(nodeId)

      const target = nodesRef.current.find(node => node.id === nodeId)
      if (target && target.data.sessionId.length > 0) {
        await window.coveApi.pty.kill({ sessionId: target.data.sessionId })
      }

      setNodes(prevNodes => {
        const now = new Date().toISOString()

        return prevNodes
          .filter(node => node.id !== nodeId)
          .map(node => {
            if (
              target?.data.kind === 'task' &&
              target.data.task?.linkedAgentNodeId &&
              node.id === target.data.task.linkedAgentNodeId &&
              node.data.kind === 'agent' &&
              node.data.agent
            ) {
              return {
                ...node,
                data: {
                  ...node.data,
                  agent: {
                    ...node.data.agent,
                    taskId: null,
                  },
                },
              }
            }

            if (
              target?.data.kind === 'agent' &&
              target.data.agent?.taskId &&
              node.id === target.data.agent.taskId &&
              node.data.kind === 'task' &&
              node.data.task
            ) {
              return {
                ...node,
                data: {
                  ...node.data,
                  task: {
                    ...node.data.task,
                    linkedAgentNodeId: null,
                    status: node.data.task.status === 'doing' ? 'todo' : node.data.task.status,
                    updatedAt: now,
                  },
                },
              }
            }

            return node
          })
      })
    },
    [clearAgentLaunchToken, setNodes],
  )

  const normalizePosition = useCallback((nodeId: string, desired: Point, size: Size): Point => {
    return findNearestFreePosition(desired, size, nodesRef.current, nodeId)
  }, [])

  const resizeNode = useCallback(
    (nodeId: string, desiredSize: Size) => {
      const node = nodesRef.current.find(item => item.id === nodeId)
      if (!node) {
        return
      }

      const boundedSize = clampSizeToNonOverlapping(
        node.position,
        desiredSize,
        MIN_SIZE,
        nodesRef.current,
        nodeId,
      )

      upsertNode({
        ...node,
        data: {
          ...node.data,
          width: boundedSize.width,
          height: boundedSize.height,
        },
      })

      onRequestPersistFlush?.()
    },
    [onRequestPersistFlush, upsertNode],
  )

  const applyPendingScrollbacks = useCallback((targetNodes: Node<TerminalNodeData>[]) => {
    const pendingScrollbacks = pendingScrollbackByNodeRef.current
    if (pendingScrollbacks.size === 0) {
      return targetNodes
    }

    let hasChanged = false

    const nextNodes = targetNodes.map(node => {
      if (node.data.kind === 'task') {
        return node
      }

      const pending = pendingScrollbacks.get(node.id)
      if (pending === undefined) {
        return node
      }

      const normalized = pending.length > 0 ? pending : null
      if (node.data.scrollback === normalized) {
        return node
      }

      hasChanged = true

      return {
        ...node,
        data: {
          ...node.data,
          scrollback: normalized,
        },
      }
    })

    pendingScrollbacks.clear()
    return hasChanged ? nextNodes : targetNodes
  }, [])

  const updateNodeScrollback = useCallback(
    (nodeId: string, scrollback: string) => {
      if (isNodeDraggingRef.current) {
        pendingScrollbackByNodeRef.current.set(nodeId, scrollback)
        return
      }

      const normalized = scrollback.length > 0 ? scrollback : null

      setNodes(
        prevNodes => {
          let hasChanged = false

          const nextNodes = prevNodes.map(node => {
            if (node.id !== nodeId || node.data.kind === 'task') {
              return node
            }

            if (node.data.scrollback === normalized) {
              return node
            }

            hasChanged = true

            return {
              ...node,
              data: {
                ...node.data,
                scrollback: normalized,
              },
            }
          })

          return hasChanged ? nextNodes : prevNodes
        },
        { syncLayout: false },
      )
    },
    [setNodes],
  )

  const updateTerminalTitle = useCallback(
    (nodeId: string, title: string) => {
      const normalizedTitle = title.trim()
      if (normalizedTitle.length === 0) {
        return
      }

      setNodes(
        prevNodes => {
          let hasChanged = false

          const nextNodes = prevNodes.map(node => {
            if (node.id !== nodeId || node.data.kind !== 'terminal') {
              return node
            }

            if (node.data.title === normalizedTitle) {
              return node
            }

            hasChanged = true
            return {
              ...node,
              data: {
                ...node.data,
                title: normalizedTitle,
              },
            }
          })

          return hasChanged ? nextNodes : prevNodes
        },
        { syncLayout: false },
      )
    },
    [setNodes],
  )

  const createNodeForSession = useCallback(
    async ({
      sessionId,
      title,
      anchor,
      kind,
      agent,
    }: CreateNodeInput): Promise<Node<TerminalNodeData> | null> => {
      const currentNodes = nodesRef.current
      const nonOverlappingPosition = findNearestFreePosition(anchor, DEFAULT_SIZE, currentNodes)
      const canPlace = isPositionAvailable(nonOverlappingPosition, DEFAULT_SIZE, currentNodes)

      if (!canPlace) {
        await window.coveApi.pty.kill({ sessionId })
        window.alert('当前视图附近没有可用空位，请先移动或关闭部分终端窗口。')
        return null
      }

      const now = new Date().toISOString()

      const nextNode: Node<TerminalNodeData> = {
        id: crypto.randomUUID(),
        type: 'terminalNode',
        position: nonOverlappingPosition,
        data: {
          sessionId,
          title,
          width: DEFAULT_SIZE.width,
          height: DEFAULT_SIZE.height,
          kind,
          status: kind === 'agent' ? 'running' : null,
          startedAt: kind === 'agent' ? now : null,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: null,
          agent: kind === 'agent' ? (agent ?? null) : null,
          task: null,
        },
        draggable: true,
        selectable: true,
      }

      setNodes(prevNodes => [...prevNodes, nextNode])
      onRequestPersistFlush?.()
      return nextNode
    },
    [onRequestPersistFlush, setNodes],
  )

  const createTaskNode = useCallback(
    (
      anchor: Point,
      title: string,
      requirement: string,
      autoGeneratedTitle: boolean,
      priority: TaskPriority,
      tags: string[],
    ): Node<TerminalNodeData> | null => {
      const currentNodes = nodesRef.current
      const nonOverlappingPosition = findNearestFreePosition(anchor, TASK_SIZE, currentNodes)
      const canPlace = isPositionAvailable(nonOverlappingPosition, TASK_SIZE, currentNodes)

      if (!canPlace) {
        window.alert('当前视图附近没有可用空位，请先移动或关闭部分窗口。')
        return null
      }

      const now = new Date().toISOString()

      const nextNode: Node<TerminalNodeData> = {
        id: crypto.randomUUID(),
        type: 'taskNode',
        position: nonOverlappingPosition,
        data: {
          sessionId: '',
          title,
          width: TASK_SIZE.width,
          height: TASK_SIZE.height,
          kind: 'task',
          status: null,
          startedAt: null,
          endedAt: null,
          exitCode: null,
          lastError: null,
          scrollback: null,
          agent: null,
          task: {
            requirement,
            status: 'todo',
            priority,
            tags,
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle,
            createdAt: now,
            updatedAt: now,
          },
        },
        draggable: true,
        selectable: true,
      }

      setNodes(prevNodes => [...prevNodes, nextNode])
      onRequestPersistFlush?.()
      return nextNode
    },
    [onRequestPersistFlush, setNodes],
  )

  return {
    nodesRef,
    pendingScrollbackByNodeRef,
    isNodeDraggingRef,
    setNodes,
    upsertNode,
    bumpAgentLaunchToken,
    clearAgentLaunchToken,
    isAgentLaunchTokenCurrent,
    closeNode,
    normalizePosition,
    resizeNode,
    applyPendingScrollbacks,
    updateNodeScrollback,
    updateTerminalTitle,
    createNodeForSession,
    createTaskNode,
  }
}
