import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp, storageKey } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Tasks (Edit & Delete)', () => {
  test('supports task edit, resize, and delete confirmation', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'task-edit-node',
          title: 'Initial Task Title',
          position: { x: 360, y: 160 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Initial requirement text',
            status: 'todo',
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
          },
        },
      ])

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()

      const inlineRequirementInput = taskNode.locator(
        '[data-testid="task-node-inline-requirement-input"]',
      )
      await expect(inlineRequirementInput).toBeVisible()
      await inlineRequirementInput.fill('Inline updated requirement from card')
      await inlineRequirementInput.blur()
      await expect(inlineRequirementInput).toHaveValue('Inline updated requirement from card')

      await taskNode.locator('[data-testid="task-node-open-editor"]').click()

      const editor = window.locator('[data-testid="workspace-task-editor"]')
      await expect(editor).toBeVisible()

      await window
        .locator('[data-testid="workspace-task-editor-title"]')
        .fill('Retry login workflow')
      await window
        .locator('[data-testid="workspace-task-editor-requirement"]')
        .fill('Implement retry with capped exponential backoff and jitter')

      await window.locator('[data-testid="workspace-task-edit-submit"]').click()

      await expect(taskNode.locator('[data-testid="task-node-inline-title-input"]')).toHaveCount(0)
      await expect(taskNode.locator('.task-node__header')).toContainText('Retry login workflow')
      await expect(inlineRequirementInput).toHaveValue(/capped exponential/)
      await expect(taskNode.locator('.task-node__inline-hint')).toHaveCount(0)

      const inlineTitleInput = taskNode.locator('[data-testid="task-node-inline-title-input"]')
      await taskNode.locator('.task-node__header').dispatchEvent('click', {
        bubbles: true,
        cancelable: true,
        detail: 2,
      })
      await expect(inlineTitleInput).toBeVisible()
      await inlineTitleInput.fill('Retry login workflow final')
      await inlineTitleInput.press('Enter')
      await expect(inlineTitleInput).toHaveCount(0)
      await expect(taskNode.locator('.task-node__header')).toContainText(
        'Retry login workflow final',
      )

      const rightResizer = taskNode.locator('[data-testid="task-resizer-right"]')
      const rightResizerBox = await rightResizer.boundingBox()
      if (!rightResizerBox) {
        throw new Error('task right resizer bounding box unavailable')
      }

      const rightStartX = rightResizerBox.x + rightResizerBox.width / 2
      const rightStartY = rightResizerBox.y + rightResizerBox.height / 2

      await window.mouse.move(rightStartX, rightStartY)
      await window.mouse.down()
      await window.mouse.move(rightStartX + 120, rightStartY + 30)
      await window.mouse.up()

      const bottomResizer = taskNode.locator('[data-testid="task-resizer-bottom"]')
      const bottomResizerBox = await bottomResizer.boundingBox()
      if (!bottomResizerBox) {
        throw new Error('task bottom resizer bounding box unavailable')
      }

      const bottomStartX = bottomResizerBox.x + bottomResizerBox.width / 2
      const bottomStartY = bottomResizerBox.y + bottomResizerBox.height / 2

      await window.mouse.move(bottomStartX, bottomStartY)
      await window.mouse.down()
      await window.mouse.move(bottomStartX + 40, bottomStartY + 100)
      await window.mouse.up()

      const resizedTask = await window.evaluate(async key => {
        void key

        const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
        if (!raw) {
          return null
        }

        const parsed = JSON.parse(raw) as {
          workspaces?: Array<{
            nodes?: Array<{
              id: string
              width: number
              height: number
              title: string
              task?: {
                requirement?: string
              }
            }>
          }>
        }

        return parsed.workspaces?.[0]?.nodes?.find(node => node.id === 'task-edit-node') ?? null
      }, storageKey)

      expect(resizedTask).toBeTruthy()
      expect(resizedTask?.width ?? 0).toBeGreaterThan(460)
      expect(resizedTask?.height ?? 0).toBeGreaterThan(280)
      expect(resizedTask?.title).toBe('Retry login workflow final')
      expect(resizedTask?.task?.requirement).toContain('capped exponential')

      await taskNode.locator('[data-testid="task-node-close"]').click()

      const deleteDialog = window.locator('[data-testid="workspace-node-delete-confirmation"]')
      await expect(deleteDialog).toBeVisible()

      await window.locator('[data-testid="workspace-node-delete-cancel"]').click()
      await expect(deleteDialog).toBeHidden()
      await expect(taskNode).toBeVisible()

      await taskNode.locator('.task-node__header').click()
      await window.keyboard.press('Backspace')
      await expect(deleteDialog).toBeVisible()
      await window.keyboard.press('Enter')

      await expect(window.locator('.task-node')).toHaveCount(0)
    } finally {
      await electronApp.close()
    }
  })
})
