import { expect, type Locator, type Page } from '@playwright/test'
import path from 'path'
import type {
  TaskAgentSessionRecord,
  WebsiteNodeData,
} from '../../src/contexts/workspace/presentation/renderer/types'
import type { CreateMountResult, ListMountsResult } from '../../src/shared/contracts/dto'
import { launchApp } from './workspace-canvas.app'
import {
  buildEchoSequenceCommand,
  buildNodeEvalCommand,
  buildPaddedNumberSequenceCommand,
  createTestUserDataDir,
  removePathWithRetry,
} from './workspace-canvas.testUtils'

export const testWorkspacePath = path.resolve(__dirname, '../../')
export const storageKey = 'opencove:m0:workspace-state'
export const viewStateStorageKey = 'opencove:m5.6:view-state'
export const seededWorkspaceId = 'workspace-seeded'
export {
  beginDragMouse,
  dragLocatorTo,
  dragMouse,
  readLocatorClientRect,
} from './workspace-canvas.gestures'
export {
  buildEchoSequenceCommand,
  buildNodeEvalCommand,
  buildPaddedNumberSequenceCommand,
  createTestUserDataDir,
  launchApp,
  removePathWithRetry,
}
export {
  readCanvasViewport,
  readWorkspaceViewState,
  selectCoveOption,
} from './workspace-canvas.viewState'

export interface SeedAgentData {
  provider: 'claude-code' | 'codex' | 'opencode' | 'gemini'
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: 'new' | 'resume'
  resumeSessionId: string | null
  resumeSessionIdVerified?: boolean
  executionDirectory: string
  expectedDirectory?: string | null
  directoryMode: 'workspace' | 'custom'
  customDirectory: string | null
  shouldCreateDirectory: boolean
}

export interface SeedTaskData {
  requirement: string
  status: 'todo' | 'doing' | 'ai_done' | 'done'
  priority?: 'low' | 'medium' | 'high' | 'urgent'
  tags?: string[]
  linkedAgentNodeId: string | null
  agentSessions?: TaskAgentSessionRecord[]
  lastRunAt: string | null
  autoGeneratedTitle: boolean
  createdAt?: string | null
  updatedAt?: string | null
}

export type SeedNoteData = { text: string }
export type SeedWebsiteData = WebsiteNodeData

export interface SeedNode {
  id: string
  title: string
  position: { x: number; y: number }
  width: number
  height: number
  kind?: 'terminal' | 'agent' | 'task' | 'note' | 'website'
  status?: 'running' | 'standby' | 'exited' | 'failed' | 'stopped' | 'restoring' | null
  startedAt?: string | null
  endedAt?: string | null
  exitCode?: number | null
  lastError?: string | null
  scrollback?: string | null
  labelColorOverride?: string | null
  executionDirectory?: string | null
  expectedDirectory?: string | null
  agent?: SeedAgentData | null
  task?: SeedTaskData | SeedNoteData | SeedWebsiteData | null
}

export interface SeedWorkspace {
  id: string
  name: string
  path: string
  nodes: SeedNode[]
  spaces?: Array<{
    id: string
    name: string
    directoryPath: string
    labelColor?: string | null
    nodeIds: string[]
    rect?: {
      x: number
      y: number
      width: number
      height: number
    } | null
  }>
  activeSpaceId?: string | null
}

function isRetryableNavigationError(error: unknown): boolean {
  const message = error instanceof Error ? error.message : String(error)
  return (
    message.includes('Execution context was destroyed') ||
    message.includes('most likely because of a navigation') ||
    message.includes('Target page, context or browser has been closed') ||
    message.includes('Navigation failed') ||
    message.includes('Navigation timeout')
  )
}

async function ensureWorkspaceMounts(window: Page, workspaces: SeedWorkspace[]): Promise<void> {
  const mountSeeds = workspaces
    .map(workspace => ({
      projectId: workspace.id,
      rootPath: workspace.path,
      name: workspace.name,
    }))
    .filter(item => item.rootPath.trim().length > 0)

  if (mountSeeds.length === 0) {
    return
  }

  await expect
    .poll(
      async () => {
        return await window.evaluate(async () => {
          try {
            await window.opencoveApi.controlSurface.invoke({
              kind: 'query',
              id: 'system.ping',
              payload: null,
            })
            return true
          } catch {
            return false
          }
        })
      },
      { timeout: 15_000 },
    )
    .toBe(true)

  await window.evaluate(async seeds => {
    const sleep = async (ms: number): Promise<void> => {
      await new Promise(resolve => setTimeout(resolve, ms))
    }

    await Promise.all(
      seeds.map(async seed => {
        const listMounts = async () => {
          return await window.opencoveApi.controlSurface.invoke<ListMountsResult>({
            kind: 'query',
            id: 'mount.list',
            payload: { projectId: seed.projectId },
          })
        }

        const removeMount = async (mountId: string) => {
          await window.opencoveApi.controlSurface.invoke({
            kind: 'command',
            id: 'mount.remove',
            payload: { mountId },
          })
        }

        const createMount = async () => {
          await window.opencoveApi.controlSurface.invoke<CreateMountResult>({
            kind: 'command',
            id: 'mount.create',
            payload: {
              projectId: seed.projectId,
              endpointId: 'local',
              rootPath: seed.rootPath,
              name: seed.name,
            },
          })
        }

        // Ensure exactly one local mount for this workspace, so space creation tests don't get blocked
        // by the target-mount picker window due to transient duplicate mounts.
        const ensureSingleMount = async (attempt: number): Promise<void> => {
          if (attempt >= 5) {
            return
          }

          const mountResult = await listMounts()
          const preferred =
            mountResult.mounts.find(
              mount => mount.endpointId === 'local' && mount.rootPath === seed.rootPath,
            ) ?? null

          if (!preferred) {
            await createMount().catch(() => undefined)
            await sleep(60)
            await ensureSingleMount(attempt + 1)
            return
          }

          const keepMountId = preferred.mountId

          await Promise.all(
            mountResult.mounts
              .filter(mount => mount.mountId !== keepMountId)
              .map(mount => removeMount(mount.mountId).catch(() => undefined)),
          )

          await sleep(80)

          const verified = await listMounts()
          const remaining = verified.mounts.filter(mount => mount.mountId !== keepMountId)
          if (remaining.length === 0) {
            return
          }

          await ensureSingleMount(attempt + 1)
        }

        await ensureSingleMount(0)
      }),
    )

    window.dispatchEvent(new Event('opencove:topology-changed'))
  }, mountSeeds)
}

export async function seedWorkspaceState(
  window: Page,
  payload: {
    activeWorkspaceId: string
    workspaces: SeedWorkspace[]
    settings?: unknown
  },
): Promise<void> {
  const seededState = {
    formatVersion: 1,
    activeWorkspaceId: payload.activeWorkspaceId,
    workspaces: payload.workspaces,
    ...(payload.settings ? { settings: payload.settings } : {}),
  }

  const trySeed = async (attempt: number): Promise<boolean> => {
    if (attempt >= 6) {
      return false
    }

    type WriteWorkspaceStateResult =
      | { ok: true }
      | { ok: false; reason: string; error: { code: string; debugMessage?: string } }
    let writeResult: WriteWorkspaceStateResult
    try {
      writeResult = await window.evaluate(
        async ({ state, viewStateKey }) => {
          window.localStorage.removeItem(viewStateKey)
          return await window.opencoveApi.persistence.writeWorkspaceStateRaw({
            raw: JSON.stringify(state),
          })
        },
        { state: seededState, viewStateKey: viewStateStorageKey },
      )
    } catch (error) {
      if (isRetryableNavigationError(error)) {
        await window
          .waitForLoadState('domcontentloaded', { timeout: 60_000 })
          .catch(() => undefined)
        return await trySeed(attempt + 1)
      }

      throw error
    }

    if (!writeResult.ok) {
      throw new Error(
        `Failed to seed workspace state: ${writeResult.reason}: ${writeResult.error.code}${
          writeResult.error.debugMessage ? `: ${writeResult.error.debugMessage}` : ''
        }`,
      )
    }

    try {
      await window.reload({ waitUntil: 'domcontentloaded', timeout: 60_000 })
      await window.waitForLoadState('load', { timeout: 15_000 }).catch(() => undefined)
    } catch {
      return await trySeed(attempt + 1)
    }

    const expectedWorkspaces = payload.workspaces.map(workspace => ({
      id: workspace.id,
      nodeIds: workspace.nodes.map(node => node.id),
    }))

    let seededReady = false
    try {
      seededReady = await window.evaluate(async workspaceExpectations => {
        const raw = await window.opencoveApi.persistence.readWorkspaceStateRaw()
        if (!raw) {
          return false
        }

        try {
          const parsed = JSON.parse(raw) as {
            workspaces?: Array<{
              id?: string
              nodes?: Array<{
                id?: string
              }>
            }>
          }

          if (!Array.isArray(parsed.workspaces)) {
            return false
          }

          const workspaceById = new Map(
            parsed.workspaces
              .filter(workspace => typeof workspace.id === 'string')
              .map(workspace => [workspace.id as string, workspace]),
          )

          return workspaceExpectations.every(expectedWorkspace => {
            const loadedWorkspace = workspaceById.get(expectedWorkspace.id)
            if (!loadedWorkspace || !Array.isArray(loadedWorkspace.nodes)) {
              return false
            }

            const loadedNodeIds = loadedWorkspace.nodes
              .map(node => (typeof node.id === 'string' ? node.id : ''))
              .filter(id => id.length > 0)

            if (loadedNodeIds.length !== expectedWorkspace.nodeIds.length) {
              return false
            }

            return expectedWorkspace.nodeIds.every(nodeId => loadedNodeIds.includes(nodeId))
          })
        } catch {
          return false
        }
      }, expectedWorkspaces)
    } catch (error) {
      if (isRetryableNavigationError(error)) {
        return await trySeed(attempt + 1)
      }

      throw error
    }

    const expectedWorkspaceCount = payload.workspaces.length
    let workspaceCount = 0
    try {
      workspaceCount = await (async () => {
        const deadline = Date.now() + 6_000
        let count = 0

        while (Date.now() < deadline) {
          // eslint-disable-next-line no-await-in-loop -- bounded UI polling
          count = await window.locator('.workspace-item').count()
          if (count >= expectedWorkspaceCount) {
            break
          }

          // eslint-disable-next-line no-await-in-loop -- bounded UI polling
          await window.waitForTimeout(50)
        }

        return count
      })()
    } catch (error) {
      if (isRetryableNavigationError(error)) {
        return await trySeed(attempt + 1)
      }

      throw error
    }
    if (seededReady && workspaceCount >= payload.workspaces.length) {
      await expect(window.locator('.app-startup-state')).toHaveCount(0)
      await expect(window.locator('.workspace-canvas .react-flow__pane').first()).toBeVisible()
      await window.waitForTimeout(80)
      await ensureWorkspaceMounts(window, payload.workspaces)
      return true
    }

    return await trySeed(attempt + 1)
  }

  const success = await trySeed(0)
  if (!success) {
    throw new Error('Failed to deterministically seed workspace state')
  }
}

export async function clearAndSeedWorkspace(
  window: Page,
  nodes: SeedNode[],
  options?: {
    settings?: unknown
    spaces?: SeedWorkspace['spaces']
    activeSpaceId?: string | null
  },
): Promise<void> {
  await seedWorkspaceState(window, {
    activeWorkspaceId: seededWorkspaceId,
    workspaces: [
      {
        id: seededWorkspaceId,
        name: path.basename(testWorkspacePath),
        path: testWorkspacePath,
        nodes,
        ...(options?.spaces ? { spaces: options.spaces } : {}),
        ...(options && 'activeSpaceId' in options ? { activeSpaceId: options.activeSpaceId } : {}),
      },
    ],
    settings:
      options?.settings && typeof options.settings === 'object' && options.settings !== null
        ? {
            standardWindowSizeBucket: 'regular',
            ...options.settings,
          }
        : {
            standardWindowSizeBucket: 'regular',
          },
  })
}

export async function clickCreateSpaceFromSelectionContextMenu(
  window: Page,
  trigger: Locator,
  options?: {
    triggerPosition?: { x: number; y: number }
    targetMountId?: string
    visibleTimeoutMs?: number
  },
): Promise<void> {
  const createSpaceAction = window.locator('[data-testid="workspace-selection-create-space"]')
  const pickerWindow = window.locator('[data-testid="workspace-space-target-mount-window"]')
  const pickerConfirm = window.locator('[data-testid="workspace-space-target-mount-confirm"]')

  await trigger.click({
    button: 'right',
    ...(options?.triggerPosition ? { position: options.triggerPosition } : {}),
  })
  await expect(createSpaceAction).toBeVisible({ timeout: options?.visibleTimeoutMs ?? 10_000 })
  await createSpaceAction.click()

  const pickerVisible = await pickerWindow
    .waitFor({ state: 'visible', timeout: 1_000 })
    .then(() => true)
    .catch(() => false)

  if (!pickerVisible) {
    return
  }

  if (options?.targetMountId) {
    await window
      .locator(`[data-testid="workspace-space-target-mount-${options.targetMountId}"]`)
      .check()
  }

  await expect(pickerConfirm).toBeEnabled()
  await pickerConfirm.click()
  await expect(pickerWindow).toHaveCount(0)
}
