import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'
import {
  installPtySessionCapture,
  readObservedResumeSessionId,
  resolveFirstAgentSessionId,
} from './workspace-canvas.agent-status-watcher.helpers'

async function seedOpenCodeTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-agent-last-message',
        title: 'Copy opencode answer',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Wait for standby and copy the last agent message',
          status: 'todo',
          priority: 'medium',
          tags: ['notes'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'opencode',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: false,
          opencode: true,
          gemini: false,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: '',
          opencode: 'opencode-e2e-model',
          gemini: '',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: [],
          opencode: ['opencode-e2e-model'],
          gemini: [],
        },
      },
    },
  )
}

test.describe('Workspace Canvas - Agent Last Message Copy (OpenCode)', () => {
  test('copies the last standby agent message from the opencode session database', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'opencode-idle-with-message',
      },
    })

    try {
      await seedOpenCodeTask(window)
      await electronApp.evaluate(async ({ clipboard }) => {
        clipboard.clear()
      })

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await installPtySessionCapture(window)
      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      let ptySessionId: string | null = null
      await expect
        .poll(async () => {
          ptySessionId = await resolveFirstAgentSessionId(window)
          return ptySessionId
        })
        .toBeTruthy()

      if (!ptySessionId) {
        throw new Error('Failed to resolve PTY session id')
      }

      await expect
        .poll(async () => await readObservedResumeSessionId(window, ptySessionId), {
          timeout: 30_000,
        })
        .toBeTruthy()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      await expect(nodeStatus).toHaveText('Standby', { timeout: 15_000 })

      const copyButton = agentNode.locator('[data-testid="terminal-node-copy-last-message"]')
      await expect(copyButton).toBeVisible()
      await copyButton.evaluate(button => {
        button.click()
      })

      await expect
        .poll(async () => {
          return await electronApp.evaluate(async ({ clipboard }) => clipboard.readText())
        })
        .toBe('OK')
    } finally {
      await electronApp.close()
    }
  })
})
