import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

async function seedCodexTask(window: Awaited<ReturnType<typeof launchApp>>['window']) {
  await clearAndSeedWorkspace(
    window,
    [
      {
        id: 'task-agent-last-message',
        title: 'Capture agent answer',
        position: { x: 180, y: 140 },
        width: 460,
        height: 280,
        kind: 'task',
        status: null,
        task: {
          requirement: 'Wait for standby and copy the last agent message',
          status: 'todo',
          priority: 'medium',
          tags: ['notes'],
          linkedAgentNodeId: null,
          lastRunAt: null,
          autoGeneratedTitle: false,
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        },
      },
    ],
    {
      settings: {
        defaultProvider: 'codex',
        customModelEnabledByProvider: {
          'claude-code': false,
          codex: true,
        },
        customModelByProvider: {
          'claude-code': '',
          codex: 'gpt-5.2-codex',
        },
        customModelOptionsByProvider: {
          'claude-code': [],
          codex: ['gpt-5.2-codex'],
        },
      },
    },
  )
}

test.describe('Workspace Canvas - Agent Last Message Copy (Working Disabled)', () => {
  test('renders the copy button disabled while working, then enables it on standby', async () => {
    const { electronApp, window } = await launchApp({
      windowMode: 'offscreen',
      env: {
        OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
        OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-commentary-then-final',
      },
    })

    try {
      await seedCodexTask(window)
      await electronApp.evaluate(async ({ clipboard }) => {
        clipboard.clear()
      })

      const taskNode = window.locator('.task-node').first()
      await expect(taskNode).toBeVisible()
      await taskNode.locator('[data-testid="task-node-run-agent"]').click()

      const agentNode = window.locator('.terminal-node').first()
      const nodeStatus = agentNode.locator('.terminal-node__status')
      const copyButton = agentNode.locator('[data-testid="terminal-node-copy-last-message"]')

      await expect(agentNode).toBeVisible()
      await expect(nodeStatus).toHaveText('Working', { timeout: 15_000 })
      await expect(copyButton).toBeVisible()
      await expect(copyButton).toBeDisabled()

      await expect(nodeStatus).toHaveText('Standby', { timeout: 30_000 })
      await expect(copyButton).toBeEnabled({ timeout: 30_000 })
      await copyButton.evaluate(button => {
        button.click()
      })

      await expect
        .poll(async () => {
          return await electronApp.evaluate(async ({ clipboard }) => clipboard.readText())
        })
        .toBe('Done.')
    } finally {
      await electronApp.close()
    }
  })
})
