import { expect, test } from '@playwright/test'
import { clearAndSeedWorkspace, launchApp } from './workspace-canvas.helpers'

test.describe('Workspace Canvas - Unified Node Chrome', () => {
  test('uses the same compact header height and button chrome across terminal, task, and note nodes', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'terminal-chrome',
          title: 'terminal-chrome',
          position: { x: 360, y: 120 },
          width: 460,
          height: 300,
        },
        {
          id: 'task-chrome',
          title: 'task chrome',
          position: { x: 900, y: 120 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Keep task chrome aligned with terminal and note nodes.',
            status: 'doing',
            priority: 'medium',
            tags: ['ui'],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
          },
        },
      ])

      const pane = window.locator('.workspace-canvas .react-flow__pane')
      await expect(pane).toBeVisible()
      await pane.dblclick({ position: { x: 380, y: 460 } })

      const terminalNode = window.locator('.terminal-node').first()
      const taskNode = window.locator('.task-node').first()
      const noteNode = window.locator('.note-node').first()

      await expect(terminalNode).toBeVisible()
      await expect(taskNode).toBeVisible()
      await expect(noteNode).toBeVisible()

      await expect(terminalNode.locator('.terminal-node__header')).toHaveCSS('height', '34px')
      await expect(taskNode.locator('.task-node__header')).toHaveCSS('height', '34px')
      await expect(noteNode.locator('.note-node__header')).toHaveCSS('height', '34px')

      const terminalClose = terminalNode.locator('.terminal-node__close')
      const taskEdit = taskNode.locator('.task-node__icon-button--edit')
      const taskClose = taskNode.locator('.task-node__icon-button--close')
      const noteClose = noteNode.locator('.note-node__close')

      await Promise.all(
        [terminalClose, taskEdit, taskClose, noteClose].flatMap(button => [
          expect(button).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)'),
          expect(button).toHaveCSS('border-top-width', '0px'),
        ]),
      )
    } finally {
      await electronApp.close()
    }
  })

  test('starts task and terminal renaming only after header double click', async () => {
    const { electronApp, window } = await launchApp()

    try {
      await clearAndSeedWorkspace(window, [
        {
          id: 'terminal-rename',
          title: 'terminal-rename',
          position: { x: 360, y: 120 },
          width: 460,
          height: 300,
        },
        {
          id: 'task-rename',
          title: 'task rename',
          position: { x: 900, y: 120 },
          width: 460,
          height: 280,
          kind: 'task',
          task: {
            requirement: 'Rename from header double click.',
            status: 'doing',
            priority: 'medium',
            tags: ['rename'],
            linkedAgentNodeId: null,
            lastRunAt: null,
            autoGeneratedTitle: false,
          },
        },
      ])

      const terminalNode = window.locator('.terminal-node').first()
      const taskNode = window.locator('.task-node').first()

      const terminalHeader = terminalNode.locator('.terminal-node__header')
      const taskHeader = taskNode.locator('.task-node__header')
      const terminalTitleInput = terminalNode.locator(
        '[data-testid="terminal-node-inline-title-input"]',
      )
      const taskTitleInput = taskNode.locator('[data-testid="task-node-inline-title-input"]')

      await terminalHeader.click({ position: { x: 72, y: 16 } })
      await taskHeader.click({ position: { x: 72, y: 16 } })
      await expect(terminalTitleInput).toHaveCount(0)
      await expect(taskTitleInput).toHaveCount(0)

      await terminalHeader.evaluate(header => {
        header.dispatchEvent(
          new MouseEvent('click', { bubbles: true, cancelable: true, detail: 2 }),
        )
      })
      await expect(terminalTitleInput).toBeVisible({ timeout: 30_000 })
      await terminalTitleInput.fill('terminal renamed')
      await terminalTitleInput.press('Enter')
      await expect(terminalTitleInput).toHaveCount(0)
      await expect(terminalHeader).toContainText('terminal renamed')

      await taskHeader.evaluate(header => {
        header.dispatchEvent(
          new MouseEvent('click', { bubbles: true, cancelable: true, detail: 2 }),
        )
      })
      await expect(taskTitleInput).toBeVisible({ timeout: 30_000 })
      await taskTitleInput.fill('task renamed')
      await taskTitleInput.press('Enter')
      await expect(taskTitleInput).toHaveCount(0)
      await expect(taskHeader).toContainText('task renamed')
    } finally {
      await electronApp.close()
    }
  })
})
