export const CURRENT_SCHEMA_COLUMNS = {
  app_meta: ['key', 'value'],
  app_settings: ['id', 'value'],
  workspaces: [
    'id',
    'name',
    'path',
    'worktrees_root',
    'pull_request_base_branch_options_json',
    'environment_variables_json',
    'space_archive_records_json',
    'viewport_x',
    'viewport_y',
    'viewport_zoom',
    'is_minimap_visible',
    'active_space_id',
    'sort_order',
  ],
  nodes: [
    'id',
    'workspace_id',
    'session_id',
    'title',
    'title_pinned_by_user',
    'position_x',
    'position_y',
    'width',
    'height',
    'kind',
    'profile_id',
    'runtime_kind',
    'terminal_geometry_json',
    'terminal_provider_hint',
    'label_color_override',
    'status',
    'started_at',
    'ended_at',
    'exit_code',
    'last_error',
    'execution_directory',
    'expected_directory',
    'agent_json',
    'task_json',
  ],
  workspace_spaces: [
    'id',
    'workspace_id',
    'name',
    'directory_path',
    'target_mount_id',
    'parent_space_id',
    'boundary_json',
    'sort_order',
    'label_color',
    'rect_x',
    'rect_y',
    'rect_width',
    'rect_height',
  ],
  workspace_space_nodes: ['space_id', 'node_id', 'sort_order'],
  node_scrollback: ['node_id', 'scrollback', 'updated_at'],
  agent_node_placeholder_scrollback: ['node_id', 'scrollback', 'updated_at'],
  browser_profile_settings: ['profile_key', 'homepage_url', 'updated_at'],
  browser_history: [
    'id',
    'profile_key',
    'url',
    'title',
    'favicon_url',
    'visit_count',
    'last_visited_at',
  ],
  browser_bookmarks: [
    'id',
    'profile_key',
    'url',
    'title',
    'favicon_url',
    'folder_id',
    'sort_order',
    'created_at',
    'updated_at',
  ],
  browser_downloads: [
    'id',
    'profile_key',
    'url',
    'filename',
    'save_path',
    'state',
    'received_bytes',
    'total_bytes',
    'started_at',
    'ended_at',
    'error',
  ],
  browser_permission_decisions: [
    'id',
    'profile_key',
    'origin',
    'permission',
    'decision',
    'updated_at',
  ],
} as const
