import { describe, expect, it } from 'vitest'
import {
  flushScheduledPersistedStateWrite,
  readPersistedState,
  schedulePersistedStateWrite,
  toPersistedState,
  writePersistedState,
  writeRawPersistedState,
} from '../../../src/renderer/src/features/workspace/utils/persistence'
import { DEFAULT_WORKSPACE_VIEWPORT } from '../../../src/renderer/src/features/workspace/types'
import type { WorkspaceState } from '../../../src/renderer/src/features/workspace/types'

class MockStorage implements Storage {
  private store = new Map<string, string>()

  public get length(): number {
    return this.store.size
  }

  public clear(): void {
    this.store.clear()
  }

  public getItem(key: string): string | null {
    return this.store.get(key) ?? null
  }

  public key(index: number): string | null {
    const keys = [...this.store.keys()]
    return keys[index] ?? null
  }

  public removeItem(key: string): void {
    this.store.delete(key)
  }

  public setItem(key: string, value: string): void {
    this.store.set(key, value)
  }
}

Object.defineProperty(window, 'localStorage', {
  configurable: true,
  writable: true,
  value: new MockStorage(),
})

describe('workspace persistence', () => {
  it('writes and reads persisted state', () => {
    const workspaces: WorkspaceState[] = [
      {
        id: 'workspace-1',
        name: 'cove',
        path: '/tmp/cove',
        viewport: { x: -320, y: 180, zoom: 1.25 },
        isMinimapVisible: false,
        spaces: [],
        activeSpaceId: null,
        nodes: [
          {
            id: 'node-1',
            type: 'terminalNode',
            position: { x: 100, y: 80 },
            data: {
              sessionId: 'session-1',
              title: 'terminal-1',
              width: 460,
              height: 300,
              kind: 'terminal',
              status: null,
              startedAt: null,
              endedAt: null,
              exitCode: null,
              lastError: null,
              scrollback: 'terminal output line 1\nterminal output line 2\n',
              agent: null,
              task: null,
            },
          },
          {
            id: 'node-task',
            type: 'taskNode',
            position: { x: 240, y: 220 },
            data: {
              sessionId: '',
              title: 'Retry Login Requests',
              width: 460,
              height: 280,
              kind: 'task',
              status: null,
              startedAt: null,
              endedAt: null,
              exitCode: null,
              lastError: null,
              scrollback: null,
              agent: null,
              task: {
                requirement: 'Implement retry with backoff and jitter',
                status: 'doing',
                linkedAgentNodeId: 'node-agent',
                lastRunAt: '2026-02-08T16:12:00.000Z',
                autoGeneratedTitle: true,
              },
            },
          },
          {
            id: 'node-agent',
            type: 'terminalNode',
            position: { x: 640, y: 120 },
            data: {
              sessionId: 'session-agent-1',
              title: 'codex · gpt-5.2-codex',
              width: 500,
              height: 320,
              kind: 'agent',
              status: 'running',
              startedAt: '2026-02-08T16:10:00.000Z',
              endedAt: null,
              exitCode: null,
              lastError: null,
              scrollback: '[cove-test-agent] codex new gpt-5.2-codex\n',
              agent: {
                provider: 'codex',
                prompt: 'Implement retry for failed request',
                model: 'gpt-5.2-codex',
                effectiveModel: 'gpt-5.2-codex',
                launchMode: 'new',
                resumeSessionId: '019c3e32-52ff-7b00-94ac-e6c5a56b4aa4',
                executionDirectory: '/tmp/cove',
                directoryMode: 'workspace',
                customDirectory: null,
                shouldCreateDirectory: false,
                taskId: 'node-task',
              },
              task: null,
            },
          },
        ],
      },
    ]

    const persisted = toPersistedState(workspaces, 'workspace-1', {
      defaultProvider: 'claude-code',
      customModelEnabledByProvider: {
        'claude-code': false,
        codex: true,
      },
      customModelByProvider: {
        'claude-code': '',
        codex: 'gpt-5.2-codex',
      },
      customModelOptionsByProvider: {
        'claude-code': ['claude-opus-4-6'],
        codex: ['gpt-5.2-codex'],
      },
      taskTitleProvider: 'codex',
      taskTitleModel: 'gpt-5.2-codex',
      taskTagOptions: ['feature', 'bug'],
      normalizeZoomOnTerminalClick: false,
    })

    writePersistedState(persisted)

    const restored = readPersistedState()

    expect(restored).not.toBeNull()
    expect(restored?.activeWorkspaceId).toBe('workspace-1')
    expect(restored?.workspaces).toHaveLength(1)
    expect(restored?.workspaces[0].viewport).toEqual({ x: -320, y: 180, zoom: 1.25 })
    expect(restored?.workspaces[0].isMinimapVisible).toBe(false)
    expect(restored?.workspaces[0].nodes).toHaveLength(3)
    expect(restored?.workspaces[0].nodes[0].title).toBe('terminal-1')
    expect(restored?.workspaces[0].nodes[0].scrollback).toContain('terminal output line 2')
    expect(restored?.workspaces[0].nodes[1].kind).toBe('task')
    expect(restored?.workspaces[0].nodes[1].task?.status).toBe('doing')
    expect(restored?.workspaces[0].nodes[2].kind).toBe('agent')
    expect(restored?.workspaces[0].nodes[2].agent?.provider).toBe('codex')
    expect(restored?.workspaces[0].spaces).toEqual([])
    expect(restored?.workspaces[0].activeSpaceId).toBeNull()
    expect(restored?.settings.defaultProvider).toBe('claude-code')
    expect(restored?.settings.customModelEnabledByProvider.codex).toBe(true)
    expect(restored?.settings.customModelByProvider.codex).toBe('gpt-5.2-codex')
    expect(restored?.settings.customModelOptionsByProvider['claude-code']).toEqual([
      'claude-opus-4-6',
    ])
    expect(restored?.settings.customModelOptionsByProvider.codex).toEqual(['gpt-5.2-codex'])
    expect(restored?.settings.taskTitleProvider).toBe('codex')
    expect(restored?.settings.taskTitleModel).toBe('gpt-5.2-codex')
    expect(restored?.settings.taskTagOptions).toEqual(['feature', 'bug'])
    expect(restored?.settings.normalizeZoomOnTerminalClick).toBe(false)
  })

  it('truncates oversized terminal scrollback', () => {
    const prefix = 'old\n'
    const suffix = 'tail\n'
    const oversized = `${prefix}${'x'.repeat(260_000)}${suffix}`

    const persisted = toPersistedState(
      [
        {
          id: 'workspace-1',
          name: 'cove',
          path: '/tmp/cove',
          viewport: { x: 0, y: 0, zoom: 1 },
          isMinimapVisible: true,
          spaces: [],
          activeSpaceId: null,
          nodes: [
            {
              id: 'terminal-1',
              type: 'terminalNode',
              position: { x: 120, y: 120 },
              data: {
                sessionId: 'session-1',
                title: 'terminal-1',
                width: 460,
                height: 300,
                kind: 'terminal',
                status: null,
                startedAt: null,
                endedAt: null,
                exitCode: null,
                lastError: null,
                scrollback: oversized,
                agent: null,
                task: null,
              },
            },
          ],
        },
      ],
      'workspace-1',
    )

    writePersistedState(persisted)

    const restored = readPersistedState()
    const restoredScrollback = restored?.workspaces[0]?.nodes[0]?.scrollback ?? ''

    expect(restoredScrollback.length).toBe(200_000)
    expect(restoredScrollback).toContain(suffix)
    expect(restoredScrollback).not.toContain(prefix)
  })

  it('falls back to default settings when persisted settings are missing', () => {
    writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: null,
        workspaces: [],
      }),
    )

    const restored = readPersistedState()
    expect(restored).not.toBeNull()
    expect(restored?.settings.defaultProvider).toBe('claude-code')
    expect(restored?.settings.customModelEnabledByProvider['claude-code']).toBe(false)
    expect(restored?.settings.customModelByProvider['claude-code']).toBe('')
    expect(restored?.settings.customModelOptionsByProvider['claude-code']).toEqual([])
    expect(restored?.settings.customModelOptionsByProvider.codex).toEqual([])
    expect(restored?.settings.taskTitleProvider).toBe('default')
    expect(restored?.settings.taskTitleModel).toBe('')
    expect(restored?.settings.taskTagOptions).toEqual([
      'feature',
      'bug',
      'refactor',
      'docs',
      'test',
    ])
    expect(restored?.settings.normalizeZoomOnTerminalClick).toBe(true)
  })

  it('fills missing workspace viewport fields for legacy payload', () => {
    writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: 'workspace-1',
        workspaces: [
          {
            id: 'workspace-1',
            name: 'cove',
            path: '/tmp/cove',
            nodes: [],
          },
        ],
        settings: {},
      }),
    )

    const restored = readPersistedState()
    expect(restored).not.toBeNull()
    expect(restored?.workspaces).toHaveLength(1)
    expect(restored?.workspaces[0].viewport).toEqual(DEFAULT_WORKSPACE_VIEWPORT)
    expect(restored?.workspaces[0].isMinimapVisible).toBe(true)
    expect(restored?.workspaces[0].spaces).toEqual([])
    expect(restored?.workspaces[0].activeSpaceId).toBeNull()
  })

  it('persists workspace spaces and active space id', () => {
    writeRawPersistedState(
      JSON.stringify({
        activeWorkspaceId: 'workspace-1',
        workspaces: [
          {
            id: 'workspace-1',
            name: 'cove',
            path: '/tmp/cove',
            viewport: { x: 0, y: 0, zoom: 1 },
            isMinimapVisible: true,
            nodes: [
              {
                id: 'node-1',
                title: 'terminal-1',
                position: { x: 120, y: 140 },
                width: 460,
                height: 300,
                kind: 'terminal',
                status: null,
                startedAt: null,
                endedAt: null,
                exitCode: null,
                lastError: null,
                scrollback: null,
                agent: null,
                task: null,
              },
            ],
            spaces: [
              {
                id: 'space-1',
                name: 'Backlog',
                directoryPath: '/tmp/cove',
                nodeIds: ['node-1'],
                rect: {
                  x: 10,
                  y: 20,
                  width: 300,
                  height: 240,
                },
              },
            ],
            activeSpaceId: 'space-1',
          },
        ],
        settings: {},
      }),
    )

    const restored = readPersistedState()
    expect(restored).not.toBeNull()
    expect(restored?.workspaces[0].spaces).toHaveLength(1)
    expect(restored?.workspaces[0].spaces[0].name).toBe('Backlog')
    expect(restored?.workspaces[0].spaces[0].directoryPath).toBe('/tmp/cove')
    expect(restored?.workspaces[0].spaces[0].nodeIds).toEqual(['node-1'])
    expect(restored?.workspaces[0].activeSpaceId).toBe('space-1')
  })

  it('returns null when stored json is invalid', () => {
    writeRawPersistedState('{')
    expect(readPersistedState()).toBeNull()
  })

  it('debounces persisted state writes and keeps latest payload', () => {
    vi.useFakeTimers()

    const setItemSpy = vi.spyOn(window.localStorage, 'setItem')

    schedulePersistedStateWrite(() => toPersistedState([], 'workspace-1'), { delayMs: 10 })
    schedulePersistedStateWrite(() => toPersistedState([], 'workspace-2'), { delayMs: 10 })

    expect(setItemSpy).not.toHaveBeenCalled()

    vi.advanceTimersByTime(10)

    expect(setItemSpy).toHaveBeenCalledTimes(1)
    const [, raw] = setItemSpy.mock.calls[0] as [string, string]
    expect(JSON.parse(raw).activeWorkspaceId).toBe('workspace-2')

    vi.useRealTimers()
    vi.restoreAllMocks()
  })

  it('flushes scheduled persisted state writes immediately', () => {
    vi.useFakeTimers()

    const setItemSpy = vi.spyOn(window.localStorage, 'setItem')

    schedulePersistedStateWrite(() => toPersistedState([], 'workspace-1'), { delayMs: 10_000 })
    flushScheduledPersistedStateWrite()

    expect(setItemSpy).toHaveBeenCalledTimes(1)

    vi.advanceTimersByTime(10_000)

    expect(setItemSpy).toHaveBeenCalledTimes(1)

    vi.useRealTimers()
    vi.restoreAllMocks()
  })

  it('ignores persistence failures (quota exceeded, disabled storage, etc.)', () => {
    const previousStorage = window.localStorage

    class ThrowingStorage extends MockStorage {
      public override setItem(_key: string, _value: string): void {
        throw new Error('QuotaExceededError')
      }
    }

    Object.defineProperty(window, 'localStorage', {
      configurable: true,
      writable: true,
      value: new ThrowingStorage(),
    })

    expect(() => {
      writePersistedState(toPersistedState([], null))
    }).not.toThrow()

    Object.defineProperty(window, 'localStorage', {
      configurable: true,
      writable: true,
      value: previousStorage,
    })
  })

  it('falls back to persisting without scrollback when quota is exceeded', () => {
    const previousStorage = window.localStorage

    class LimitedStorage extends MockStorage {
      public constructor(private readonly maxBytes: number) {
        super()
      }

      public override setItem(key: string, value: string): void {
        if (value.length > this.maxBytes) {
          const error =
            typeof DOMException === 'undefined'
              ? Object.assign(new Error('Quota exceeded'), { name: 'QuotaExceededError' })
              : new DOMException('Quota exceeded', 'QuotaExceededError')
          throw error
        }

        super.setItem(key, value)
      }
    }

    Object.defineProperty(window, 'localStorage', {
      configurable: true,
      writable: true,
      value: new LimitedStorage(1500),
    })

    const state = toPersistedState(
      [
        {
          id: 'workspace-1',
          name: 'cove',
          path: '/tmp/cove',
          viewport: { x: 0, y: 0, zoom: 1 },
          isMinimapVisible: true,
          spaces: [],
          activeSpaceId: null,
          nodes: [
            {
              id: 'terminal-1',
              type: 'terminalNode',
              position: { x: 120, y: 120 },
              data: {
                sessionId: 'session-1',
                title: 'terminal-1',
                width: 460,
                height: 300,
                kind: 'terminal',
                status: null,
                startedAt: null,
                endedAt: null,
                exitCode: null,
                lastError: null,
                scrollback: 'x'.repeat(5000),
                agent: null,
                task: null,
              },
            },
          ],
        },
      ],
      'workspace-1',
    )

    const result = writePersistedState(state)
    expect(result.ok).toBe(true)
    expect(result.ok ? result.level : null).toBe('no_scrollback')

    const restored = readPersistedState()
    expect(restored?.workspaces[0]?.nodes[0]?.scrollback).toBeNull()

    Object.defineProperty(window, 'localStorage', {
      configurable: true,
      writable: true,
      value: previousStorage,
    })
  })
})
